### ISSUE TITLE
[BUG] 无法连接数据库

### ISSUE THREAD

**Issue by scientificworld** [Icalingua-plus-plus/Icalingua-plus-plus#602]
**Describe the bug / 描述**
登录时提示无法连接数据库

**Screenshots / 截图**
<img width="266" alt="截屏2023-03-05 19 29 48" src="https://user-images.githubusercontent.com/30764166/222957834-925028d1-04ba-4386-b71a-547d1dd4c546.png">

**System information / 系统信息**
 - OS: macOS 12.6.3
 - Version: 2.9.1

**Additional context / 附加信息**
Command line output:
```
Knex: run
$ npm install sqlite3 --save
Cannot find module '/Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'
Require stack:
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/dialects/index.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/index.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/knex.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/dist/electron/main.js
-
Error: Cannot find module '/Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'
Require stack:
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/dialects/index.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/index.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/knex.js
- /Applications/Icalingua++.app/Contents/Resources/app.asar/dist/electron/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
{"level":"error","message":{"e":"Error: Knex: run\n$ npm install sqlite3 --save\nCannot find module '/Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'\nRequire stack:\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/dialects/index.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/knex-builder/internal/config-resolver.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/index.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/knex.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/dist/electron/main.js\n- ","errMsg":"Knex: run\n$ npm install sqlite3 --save\nCannot find module '/Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'\nRequire stack:\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/dialects/index.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/knex-builder/internal/config-resolver.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/lib/index.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/knex/knex.js\n- /Applications/Icalingua++.app/Contents/Resources/app.asar/dist/electron/main.js\n- ","errname":"Error"},"service":"eqq-service"}
```

**Comment by scientificworld** [comment]
Problem still exists after upgraded to 2.9.2.

**Comment by scientificworld** [comment]
Move `napi-v6-darwin-unknown-x64` to `napi-v6-darwin-unknown-arm64` and repack asar archive, but still can't connect to the db.

```
$ npm install sqlite3 --save
dlopen(/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf, 0x0001): tried: '/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/private/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
Error: dlopen(/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf, 0x0001): tried: '/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/private/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Applications/Icalingua++.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
{"level":"error","message":{"e":"Error: Knex: run\n$ npm install sqlite3 --save\ndlopen(/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf, 0x0001): tried: '/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/private/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))","errMsg":"Knex: run\n$ npm install sqlite3 --save\ndlopen(/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf, 0x0001): tried: '/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/private/var/folders/x3/6cjmpyss0xsgdw9d1f_8qfx40000gn/T/.Icalingua.sVjBrf' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))","errname":"Error"},"service":"eqq-service"}
```

**Comment by scientificworld** [comment]
2.9.0 do not have this issue... Maybe caused by commit 471a90a?

**Comment by scientificworld** [comment]
Seems fixed in 2.9.3.
